//
//  Postcard.swift
//  Listr
//
//  Created by Felix on 10/19/25.
//

import SwiftUI
import Foundation
import FirebaseFirestore

struct PostcardDetails: Codable, Identifiable {
    @DocumentID var id: String?

    var batchID: String
    var scannedAt: Date
    var status: PostcardStatus
    var frontImageURLString: String
    var backImageURLString: String
    var aiData: PostcardAIData
    
    var frontImageURL: URL? {
        URL(string: frontImageURLString)
    }

    var backImageURL: URL? {
        URL(string: backImageURLString)
    }
}

extension PostcardDetails {
    init(
        batchID: String,
        scannedAt: Date,
        frontImageURLString: String,
        backImageURLString: String,
        aiData: PostcardAIData
    ) {
        self.batchID = batchID
        self.scannedAt = scannedAt
        self.frontImageURLString = frontImageURLString
        self.backImageURLString = backImageURLString
        self.aiData = aiData

        self.status = PostcardDetails.containsUnknownFields(in: aiData)
            ? .needsReview
            : .readyToList
    }
}

extension PostcardDetails {
    private static let unknownTokens = ["", "Unknown", "Unposted", "None"] // todo fix default values, for example when user deletes a field to empty, should it remain blank or default to some value..
    
    // boolean function that returns whether fields generated by ai contain unknown values. meaning ai wasn't able to successfully extract data
    private static func containsUnknownFields(in data: PostcardAIData) -> Bool {
        let fieldsToCheck = [
            data.era,
            data.type.material,
            data.type.style
        ]

        return fieldsToCheck.contains { value in
            unknownTokens.contains { token in
                value.localizedCaseInsensitiveContains(token)
            }
        }
    }
}

extension PostcardDetails {
    // must be mutating to change its properties
    mutating func update(aiData newAIData: PostcardAIData) {
        aiData = newAIData

        // Once a postcard is listed or sold, editing its details shouldn't change its status
        if status == .needsReview || status == .readyToList {
            status = Self.containsUnknownFields(in: newAIData) ? .needsReview : .readyToList
        }
    }
}

enum PostcardStatus: String, Codable, CaseIterable, Equatable {
    case needsReview = "needs review"
    case readyToList = "ready to list"
    case listed = "listed"
    case sold = "sold"
}

extension PostcardStatus {
    var color: Color {
        switch self {
        case .readyToList:
            return .yellow
        case .needsReview:
            return .red
        case .listed:
            return .green
        case .sold:
            return .orange
        }
    }
}

